name: Release
on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  staging:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.DEVELOP_DB_PASSWORD }}
      PROJECT_ID: ${{ secrets.DEVELOP_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref $PROJECT_ID -p ${{ secrets.DEVELOP_DB_PASSWORD }}
      - run: supabase db push -p ${{ secrets.DEVELOP_DB_PASSWORD }}
      - run: supabase link --project-ref $PROJECT_ID
      - run: supabase db push
